### ISSUE TITLE
Rocket-chat openshift OKD 3.11 /app/bundle/programs/server/node_modules/fibers/future.js:280 						throw(ex);

### ISSUE THREAD

**Issue by golgotow** [RocketChat/docs-old#1530]
Hi,

is this app still works on openshift ? on our test lab in OKD 3.11 this ends like below.

﻿/app/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^
Error: Error: Unable to find Mongodb Oplog. You must run the server with oplog enabled. Try the following:
				1. Start your mongodb in a replicaset mode: mongod --smallfiles --oplogSize 128 --replSet rs0
				2. Start the replicaset via mongodb shell: mongo mongo/meteor --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"
				3. Start your instance with OPLOG configuration: export MONGO_OPLOG_URL=mongodb://localhost:27017/local MONGO_URL=mongodb://localhost:27017/meteor node main.js
				
    at BaseDb.handleListener (app/models/server/models/_BaseDb.js:51:11)
    at emitTwo (events.js:126:13)
    at BaseDb.emit (events.js:214:7)
    at _addListener (events.js:249:14)
    at BaseDb.addListener (events.js:297:10)
    at new Base (app/models/server/models/_Base.js:21:12)
    at new Settings (app/models/server/models/Settings.js:5:3)
    at Settings.js (app/models/server/models/Settings.js:243:16)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at settings.js (app/settings/server/functions/settings.js:1:251)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (app/settings/server/index.js:1:60)

Best Regards,

**Comment by Warriorgiroro** [comment]
same error here, but i am using docker-compose single node deploy

**Comment by Rodriq** [comment]
It is recommended you follow the docker/docker compose path for deployment. It can be seen in the docs here https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose
