### ISSUE TITLE
mongodb authentication issue

### ISSUE THREAD

**Issue by ghost** [RocketChat/docs-old#210]
I'm trying to set the environment variables to run rocketchat snap in ubuntu 16.04 as follows:
<pre>
Export MONGO_URL = mongodb: // user: password @ localhost: 27017 / parties
Export ROOT_URL = https: //chat.mysite.com
Export Port = 3000

-/etc/mongod.conf - security.authenticacion: enabled
</pre>
when I run: 
<pre>$ Snap run rocketchat-server</pre>, I receive the following error message:
<pre>
MongoError: not authorized on parties to execute command { listIndexes: "users", cursor: {} }
    at Object.Future.wait (/snap/rocketchat-server/451/node_modules/fibers/future.js:449:15)
    at MongoConnection._ensureIndex (meteor://💻app/packages/mongo/mongo_driver.js:828:10)
    at null.Mongo.Collection._ensureIndex (meteor://💻app/packages/mongo/collection.js:685:20)
    at setupUsersCollection (meteor://💻app/packages/accounts-base/accounts_server.js:1491:9)
    at new AccountsServer (meteor://💻app/packages/accounts-base/accounts_server.js:51:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (meteor://💻app/packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:188:9)
    at require (packages/modules-runtime.js:111:16)
    at /snap/rocketchat-server/451/programs/server/packages/accounts-base.js:1972:15
    at /snap/rocketchat-server/451/programs/server/packages/accounts-base.js:1983:3
    - - - - -
    at Function.MongoError.create (/snap/rocketchat-server/451/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/snap/rocketchat-server/451/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /snap/rocketchat-server/451/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
</pre>

However, if I run in console <pre>mongo -u user -p password parties</pre> I have no authentication problems. Can someone help me?

**Comment by ghost** [comment]
closed and passed to https://github.com/RocketChat/Rocket.Chat/issues/5912
